### ISSUE TITLE
Add Black Friday page

### ISSUE THREAD

**Issue by wkenned1** [rockthejvm/rockthejvm-site#155]

**Comment by wkenned1** [comment]
@daniel-ciocirlan please add the discounted course prices to the prices map [here](https://github.com/rockthejvm/rockthejvm-site/blob/71fb12a9c23b686b5a05308b7df5eb1557a87efe/src/layouts/HolidayLayout.astro#L26). The second value in each pair represents the discounted price.

**Comment by wkenned1** [comment]
@daniel-ciocirlan Please send us the files for the images in the following screenshots, ideally in svg format.

![image](https://github.com/user-attachments/assets/ade1e1bc-acd6-4d9a-9253-d31cf9747cbc)

![image](https://github.com/user-attachments/assets/56d78d6e-2b3c-4f50-9f50-0ef8db16969a)

**Comment by andreilgeorgescu** [comment]
Right now we're only displaying the 26 courses that are on the courses index page. Do you want every single course on your site including the old ones to be shown? What about displaying free courses?

Also is the black Friday bundle going to include every single course on your website including the old ones?

**Comment by daniel-ciocirlan** [comment]
Yes, the BF bundle contains all courses, including the old ones.

I would like to show all courses except the Akka Classic ones, and include the free courses as well.

I’ll send you the SVGs and the prices as soon as I can.
